# Generated by Django 6.0.2 on 2026-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
