# Generated by Django 6.0.2 on 2026-02-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_time',
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_of_day',
            field=models.CharField(choices=[('MORNING', 'Mañana (5:00 - 12:00)'), ('AFTERNOON', 'Tarde (12:00 - 20:00)'), ('EVENING', 'Noche (20:00 - 5:00)'), ('ALL', 'Todo el día')], default='ALL', max_length=10),
        ),
    ]
